Repository DataDog/opentelemetry-mapping-go, pull requests merged in 2023-08, with the labels that each got.

#144 Prerelease pkgs v0.5.5
  .chloggen/otel_744_add_resource_attrs_to_log.yaml
  .chloggen/stanley.liu_update-jvm-loaded-classes.yaml
  CHANGELOG.md
  pkg/inframetadata/go.mod
  pkg/otlp/logs/go.mod
  pkg/otlp/metrics/go.mod
  pkg/quantile/go.mod
  versions.yaml
Labels: Skip Changelog

#145 Update datadog-agent dependency versions
  pkg/otlp/metrics/go.mod
  pkg/otlp/metrics/go.sum
Labels: dependencies, Skip Changelog

#146 Prerelease pkgs v0.6.0
  pkg/inframetadata/go.mod
  pkg/otlp/logs/go.mod
  pkg/otlp/metrics/go.mod
  pkg/quantile/go.mod
  versions.yaml
Labels: Skip Changelog

#151 Prerelease pkgs v0.7.0
  .chloggen/fix-metric-mapping.yaml
  .chloggen/mx-psi_histo-min-max.yaml
  CHANGELOG.md
  pkg/inframetadata/go.mod
  pkg/otlp/logs/go.mod
  pkg/otlp/metrics/go.mod
  pkg/quantile/go.mod
  versions.yaml
Labels: Skip Changelog

#157 Pool the overflow list in `sparseStore.trimLeft`
  pkg/quantile/pool.go
  pkg/quantile/store.go
Labels: enhancement, Skip Changelog
