Repository DataDog/opentelemetry-mapping-go, pull requests merged in 2024-12, with the labels that each got.

#413 [all] Bump required minimum Go version to 1.22
  .chloggen/bump-go-version.yaml
  .github/workflows/test.yaml
  Makefile
  pkg/inframetadata/go.mod
  pkg/inframetadata/go.sum
  pkg/inframetadata/gohai/internal/gohaitest/go.mod
  pkg/internal/sketchtest/go.mod
  pkg/otlp/attributes/go.mod
  pkg/otlp/attributes/go.sum
  pkg/otlp/logs/go.mod
  pkg/otlp/logs/go.sum
  pkg/otlp/metrics/go.mod
  pkg/otlp/metrics/go.sum
  pkg/quantile/go.mod
Labels: dependencies

#410 Remove unused code
  pkg/otlp/metrics/metrics_translator_benchmark_test.go
Labels: Skip Changelog

#412 [pkg/otlp/logs] upgrade datadog-api-client-go version
  pkg/otlp/logs/go.mod
  pkg/otlp/logs/go.sum
  pkg/otlp/logs/transform.go
  pkg/otlp/logs/transform_test.go
Labels: dependencies, Skip Changelog

#415 [all] upgrade all otel package versions
  LICENSE-3rdparty.csv
  pkg/inframetadata/go.mod
  pkg/inframetadata/go.sum
  pkg/inframetadata/gohai/internal/gohaitest/go.mod
  pkg/inframetadata/gohai/internal/gohaitest/go.sum
  pkg/otlp/attributes/go.mod
  pkg/otlp/attributes/go.sum
  pkg/otlp/logs/go.mod
  pkg/otlp/logs/go.sum
  pkg/otlp/metrics/go.mod
  pkg/otlp/metrics/go.sum
Labels: dependencies, Skip Changelog

#416 Prerelease pkgs v0.22.0
  .chloggen/bump-go-version.yaml
  CHANGELOG.md
  pkg/inframetadata/go.mod
  pkg/otlp/logs/go.mod
  pkg/otlp/metrics/go.mod
  pkg/quantile/go.mod
  versions.yaml
Labels: Skip Changelog
